### ISSUE TITLE
[proposal] Use time.Duration for time specification

### ISSUE THREAD

**Issue by kortschak** [yobert/alsa#10]
Currently `alsa.NewBufferSeconds` takes an `int` to specify the length of the buffer. It would be nice to support sub-second times, and also reflect that the time is a duration by changing the signature to (or adding) `NewBuffer(time.Duration)`.

Does this sound reasonable?

**Comment by yobert** [comment]
Sounds great! Yeah I was just being lazy :D  I think using a time.Duration, renaming the function to NewBuffer, and rounding to the nearest frame count would be a great improvement!

Feel free to PR, or I can do it if you're busy.

**Comment by kortschak** [comment]
I was looking into it and it's not entirely clear to me how the frames per buffer is specified. I looked into the ALSA docs, but their not as clear as they could be, so if you can point me to something that explains this, I'll be happy to take it on. Otherwise I'll bow out in your favour.
