### ISSUE TITLE
Continuous recording?

### ISSUE THREAD

**Issue by Xeoncross** [yobert/alsa#11]
Looking at the recorder example it seems that a continuous monitor could be setup by looping over a `select` checking a `<-done` channel, else [reading more input into a buffer](https://github.com/yobert/alsa/blob/master/cmd/record/main.go#L115-L121).

It looks like you are doing something related with the [echoback example](https://github.com/yobert/alsa/blob/master/cmd/echoback/main.go#L161).

**Comment by yobert** [comment]
Yeah! That makes sense! That echoback code is pretty buggy, but you're absolutely right about the semantics.  I try to think of it as reading and writing from a network socket.  Anyways, feel free to send a PR!
