### ISSUE TITLE
Some ioctls are invalid on arm

### ISSUE THREAD

**Issue by ironiridis** [yobert/alsa#2]
It appears that lengths for data structures vary depending on architecture. Caught here:

https://github.com/yobert/alsa/blob/master/device.go#L233

The native ARM (ie 32-bit, specifically not ARM8/aarch64) ALSA utilities encode an ioctl with a length of 604, not 608. I suspect the length descrepency comes down to this:

https://github.com/yobert/alsa/blob/master/misc/types.go#L4

since `snd_pcm_uframes_t` is an `unsigned long` according to [the API reference](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#gab01fcfe9b97382a8d3f2027c664b8b8a) and the difference of that datatype between 64 bits and 32 bits is suspiciously close to 4 bytes.

I'll investigate and see about having that value get computed rather than hard-coded.

**Comment by ironiridis** [comment]
And to be clear, there would need to be some [architecture-dependent compilation](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool) to coincide with that computed length.

**Comment by yobert** [comment]
Yeah, doing it without CGO means throwing away years of compatibility work on different platforms. It makes me very sad.

**Comment by ironiridis** [comment]
Let me retest on my arm rig to be sure, but this is probably closed by #5.

Thank you for merging!

**Comment by yobert** [comment]
I'm going to go ahead and close this-- but please let me know if I should reopen. Thanks!
